name: Heroku Nodejs Web App Deploy
on:
  push:
    branches:    
    - 'master'
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Git configure and update the API token
      env:
        KKBOX_CLIENT_ID: ${{ secrets.KKBOX_CLIENT_ID }}
        KKBOX_CLIENT_SECRET: ${{ secrets.KKBOX_CLIENT_SECRET }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        git config --global user.name "github_actions"
        git config --global user.email "github_actions@noreply"
        curl -d "grant_type=client_credentials&&client_id=$KKBOX_CLIENT_ID&client_secret=$KKBOX_CLIENT_SECRET" https://account.kkbox.com/oauth2/token | cut -d'"' -f 4 | xargs -I {} sed -ie "s/KKBOX_API_TOKEN/{}/g" service.js
        sed -ie "s/YOUTUBE_API_KEY/$YOUTUBE_API_KEY/g" service.js
        git add service.js && git commit -m'Update the API token'
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "shrouded-ocean-69872"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        git push heroku HEAD:master -f
